// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzqvaxcbwrfaqhwumoqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6cXZheGNid3JmYXFod3Vtb3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzc4NzMsImV4cCI6MjA3MzAxMzg3M30.7F5SODN8SJgdC7pkQphWy7ThYwEYAgqiXt42-ceBIAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});